# Generated by Django 6.0.4 on 2026-04-13 05:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('action', models.CharField(db_index=True, max_length=64)),
                ('detail', models.CharField(blank=True, default='', max_length=512)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_auditlog',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserMailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settings_json', models.JSONField(blank=True, default=dict)),
                ('smtp_password_enc', models.TextField(blank=True, default='')),
                ('imap_password_enc', models.TextField(blank=True, default='')),
                ('llm_api_key_enc', models.TextField(blank=True, default='')),
                ('google_oauth_token_enc', models.TextField(blank=True, default='')),
                ('client_secret_json_enc', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mail_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_usermailsettings',
            },
        ),
    ]
