# Generated by Django 5.2.13 on 2026-04-26 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_password_reset_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, default='', max_length=64)),
                ('message_id', models.CharField(default='', max_length=255)),
                ('meta_json', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'core_processedmeta',
                'constraints': [models.UniqueConstraint(fields=('tenant_id', 'message_id'), name='uq_processedmeta_tenant_message')],
            },
        ),
        migrations.CreateModel(
            name='QueueItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, default='', max_length=64)),
                ('message_id', models.CharField(default='', max_length=255)),
                ('status', models.CharField(db_index=True, default='', max_length=32)),
                ('details_json', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                'db_table': 'core_queueitem',
                'indexes': [models.Index(fields=['tenant_id', '-updated_at'], name='idx_queueitem_tenant_updated')],
                'constraints': [models.UniqueConstraint(fields=('tenant_id', 'message_id'), name='uq_queueitem_tenant_message')],
            },
        ),
    ]
