# Generated by Django 5.2.12 on 2026-09-29 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_marketing_landing_page_rag'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketinglandingpage',
            name='metrics_kicker',
            field=models.CharField(default='Pipeline facts', max_length=40),
        ),
        migrations.AddField(
            model_name='marketinglandingpage',
            name='metrics_sub',
            field=models.TextField(default='Retrieval depth, draft speed, and coverage that stays on while the inbox is open.'),
        ),
        migrations.AddField(
            model_name='marketinglandingpage',
            name='metrics_title',
            field=models.CharField(default='The numbers behind every reply', max_length=120),
        ),
    ]
