# Generated by Django 5.2.12 on 2026-09-29 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_landing_metrics_header'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketingpricingsettings',
            name='demo_note',
            field=models.TextField(blank=True, default='', help_text='Deprecated — left blank. Use intro only.'),
        ),
        migrations.AlterField(
            model_name='marketingpricingsettings',
            name='intro',
            field=models.TextField(default='Choose a plan below, then connect in Setup. Starter includes 20 auto-sends; Pro bills monthly. Drafts never use tokens.'),
        ),
    ]
