# Generated by Django 5.2.12 on 2026-09-29 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_pricing_single_intro'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marketinglandingpage',
            options={'verbose_name': 'landing page', 'verbose_name_plural': 'landing page'},
        ),
        migrations.AlterModelOptions(
            name='marketingragitem',
            options={'ordering': ['sort_order', 'id'], 'verbose_name': 'grounding point', 'verbose_name_plural': 'grounding points'},
        ),
    ]
