# Generated by Django 5.2.12 on 2026-10-04 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_remove_landing_metrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketingreview',
            name='photo',
            field=models.ImageField(blank=True, help_text='Optional portrait for the homepage review slider.', null=True, upload_to='marketing/reviews/'),
        ),
        migrations.AlterField(
            model_name='marketinglandingpage',
            name='hero_cta_primary',
            field=models.CharField(default='Get Started', max_length=80),
        ),
        migrations.AlterField(
            model_name='marketinglandingpage',
            name='hero_overline',
            field=models.CharField(default='AI for your inbox', max_length=80),
        ),
        migrations.AlterField(
            model_name='marketinglandingpage',
            name='hero_sub_html',
            field=models.TextField(default='Connect Gmail or IMAP and let MailPilot draft or send replies grounded in your knowledge base - accurate answers from your docs, not generic chatbot filler.', help_text='Supports light HTML (e.g. <b>).'),
        ),
        migrations.AlterField(
            model_name='marketinglandingpage',
            name='hero_title_before',
            field=models.CharField(default='AI email automation,', max_length=120),
        ),
        migrations.AlterField(
            model_name='marketinglandingpage',
            name='hero_title_highlight',
            field=models.CharField(default='live in minutes', max_length=80),
        ),
        migrations.AlterField(
            model_name='marketinglandingpage',
            name='hiw_sub',
            field=models.TextField(default='Six steps from poll to send—inbox to queue, grounded in your knowledge base.'),
        ),
        migrations.AlterField(
            model_name='marketinglandingpage',
            name='rag_title_html',
            field=models.CharField(default='Grounded in your docs', help_text='Supports light HTML (e.g. <em>).', max_length=200),
        ),
    ]
