# Generated by Django 5.2.12 on 2026-10-04 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_marketing_review_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketinglandingpage',
            name='cta_image_1',
            field=models.ImageField(blank=True, help_text='Floating agent — bottom left. Leave empty to use the default.', null=True, upload_to='marketing/cta/'),
        ),
        migrations.AddField(
            model_name='marketinglandingpage',
            name='cta_image_2',
            field=models.ImageField(blank=True, help_text='Floating agent — top right. Leave empty to use the default.', null=True, upload_to='marketing/cta/'),
        ),
        migrations.AddField(
            model_name='marketinglandingpage',
            name='cta_image_3',
            field=models.ImageField(blank=True, help_text='Floating agent — top left. Leave empty to use the default.', null=True, upload_to='marketing/cta/'),
        ),
        migrations.AlterField(
            model_name='marketinglandingpage',
            name='cta_sub',
            field=models.CharField(default='Get full access. No credit card required.', max_length=200),
        ),
    ]
